version: '3.8'
networks:
  rpc_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24

services:
  registry:
    build: .
    command: python registry/registry.py -p 9999
    ports:
      - "9999:9999"
    networks:
      rpc_network:
        ipv4_address: 192.168.1.10

  server1:
    build: .
    command: python server/server.py -p 12345
    ports:
      - "12345:12345"
    depends_on:
      - registry
    networks:
      rpc_network:
        ipv4_address: 192.168.1.11

  server2:
    build: .
    command: python server/server.py -p 12346
    ports:
      - "12346:12346"
    depends_on:
      - registry
    networks:
      rpc_network:
        ipv4_address: 192.168.1.12

  client1:
    build: .
    command: python client/client.py
    depends_on:
      - server2
    networks:
      rpc_network:
        ipv4_address: 192.168.1.13
